[package]
name = "braid-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "braid command line"

[[bin]]
name = "braid"
path = "src/main.rs"

[dependencies]
braid-model = { path = "../braid-model" }
braid-tama = { path = "../braid-tama" }
braid-flair = { path = "../braid-flair" }
braid-taco = { path = "../braid-taco" }
braid-scotch = { path = "../braid-scotch" }
clap = { version = "4", features = ["derive"] }
